openapi: 3.0.3
info:
  title: Earth meter API
  description: An API to upload Google takeout data and see walking statistics compared to circumference of Earth.
  version: 1.0.0
paths:
  /takeout:
    post:
      operationId: uploadTakeout
      summary: Upload Google takeout data
      tags:
        - Upload
      requestBody:
        description: Google takeout data as ZIP archive
        content:
          application/zip:
            schema:
              type: string
              format: binary
      responses:
        200:
          description: Takeout was uploaded well
        422:
          description: Basic validation of Google takeout data didn't pass
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetail"
  /walk-history/{user}:
    get:
      operationId: getWalkHistory
      summary: Retrieve a quarterly history of walking
      tags:
        - Walking History
      parameters:
        - name: user
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          $ref: '#/components/responses/WalkHistoryResponse'
components:
  schemas:
    ProblemDetail:
      type: object
      properties:
        type:
          type: string
          example: "https://example.com/probs/item-not-found"
        title:
          type: string
          example: "Item Not Found"
        status:
          type: integer
          example: 404
        detail:
          type: string
          example: "The item with the given ID was not found."
  responses:
    WalkHistoryResponse:
      description: Successfully return quarter history.
      content:
        application/json:
          schema:
            type: object
            properties:
              overallDistance:
                type: integer
                format: int64
              years:
                type: array
                items:
                  type: object
                  properties:
                    year:
                      type: number
                      format: int32
                    quarters:
                      type: object
                      additionalProperties:
                        type: integer
                        format: int64
