repositories:
  - name: postgres-operator-charts
    url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  - name: postgres-operator-ui-charts
    url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui

releases:
  - name: database-configuration
    chart: charts/database/configuration
    values:
      - values.yaml.gotmpl