apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: examples.oleksiyp.github.io
spec:
  group: oleksiyp.github.io
  names:
    plural: examples
    singular: example
    kind: Example
    shortNames:
      - example
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                size:
                  type: integer
                name:
                  type: string
            status:
              type: object
              properties:
                currentSize:
                  type: integer
                currentName:
                  type: string
    - name: v2
      served: true
      storage: false
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                sz:
                  type: integer
                name:
                  type: string
            status:
              type: object
              properties:
                currentSz:
                  type: integer
                currentName:
                  type: string

      subresources:
        status: {}