openapi: 3.0.3
info:
  title: Simple API with Error Handling
  description: A simple API example using OpenAPI 3.0.3 with errors handled as problem details.
  version: 1.0.0
paths:
  /items:
    get:
      operationId: getItems
      summary: Retrieve a list of items
      responses:
        "200":
          description: A list of items
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    id:
                      type: integer
                    name:
                      type: string
  /items/{id}:
    get:
      operationId: getItem
      summary: Retrieve an item by ID
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: An item object
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: integer
                  name:
                    type: string
        "404":
          description: Item not found
          content:
            application/problem+json:
              schema:
                $ref: "#/components/schemas/ProblemDetail"
components:
  schemas:
    ProblemDetail:
      type: object
      properties:
        type:
          type: string
          example: "https://example.com/probs/item-not-found"
        title:
          type: string
          example: "Item Not Found"
        status:
          type: integer
          example: 404
        detail:
          type: string
          example: "The item with the given ID was not found."
