apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: {{ .Values.letsEncrypt.account }}
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt
    solvers:
    - dns01:
        cloudflare:
          email: {{ .Values.letsEncrypt.account }}
          apiKeySecretRef:
            name: letsencrypt-cloudflare
            key: apikey
        selector:
          dnsZones:
            {{ .Values.letsEncrypt.dnsZone | toYaml | nindent 12 }}
