apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}-keystore
  labels:
    {{- include "backend.labels" . | nindent 4 }}
stringData:
  keystorePassword: {{ .Values.tls.keystore.password | quote }}