apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
stringData:
  application-kubernetes-secret.yaml: |-
    {{- $props := tpl (.Files.Get "files/secret-properties.yaml.gotmpl") . | fromYaml -}}
    {{ merge $props .Values.secretProperties | toYaml | nindent 4 }}