kind: "postgresql"
apiVersion: "acid.zalan.do/v1"
metadata:
  name: page-with-db
  labels:
    team: page-with-db

spec:
  teamId: "dev"
  numberOfInstances: 1

  postgresql:
    version: "16"

  preparedDatabases:
    page_with_db:
      defaultUsers: true
      schemas:
        backend:
          defaultUsers: true

  volume:
    size: "10Gi"

  resources:
    requests:
      cpu: 100m
      memory: 100Mi
    limits:
      cpu: 500m
      memory: 500Mi