debug:
  enabled: true

tls:
  enabled: true
  keystore:
    issuerRef:
      name: internal-ca
  truststore:
    ref:
      name: internal-ca-bundle

ingress:
  enabled: true
  className: internal
  hosts:
    - host: page-with-db.int.zengarden.space
      paths:
        - path: /api/items/v1
          pathType: ImplementationSpecific

properties:
  spring:
    datasource:
      url: jdbc:postgresql://page-with-db/page_with_db
      username: ${DB_USERNAME}
      schema: backend
    liquibase:
      user: ${DB_OWNER_USERNAME}

secretProperties:
  spring:
    datasource:
      password: ${DB_PASSWORD}
    liquibase:
      password: ${DB_OWNER_PASSWORD}

envFrom:
  DB_USERNAME:
    secretKeyRef:
      name: page-with-db-backend-writer-user.page-with-db.credentials.postgresql.acid.zalan.do
      key: username
  DB_PASSWORD:
    secretKeyRef:
      name: page-with-db-backend-writer-user.page-with-db.credentials.postgresql.acid.zalan.do
      key: password
  DB_OWNER_USERNAME:
    secretKeyRef:
      name: page-with-db-backend-owner-user.page-with-db.credentials.postgresql.acid.zalan.do
      key: username
  DB_OWNER_PASSWORD:
    secretKeyRef:
      name: page-with-db-backend-owner-user.page-with-db.credentials.postgresql.acid.zalan.do
      key: password
