apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: identity-server
spec:
  secretName: identity-server-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  commonName: "identity-server.identity-infra.svc.cluster.local"
  dnsNames:
    - "identity-server.identity-infra.svc.cluster.local"
    - "identity-server.identity-infra"
    - "identity-server"
