apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
data:
  nginx.conf: |-
    {{- tpl (.Files.Get "files/nginx.conf.gotmpl") . | nindent 4 }}
