environments:
  default:
    values:
    - instances/zengarden.space/values.yaml.gotmpl

repositories:
  - name: bitnami
    url: https://charts.bitnami.com/bitnami
  - name: cloudflare
    url: https://cloudflare.github.io/helm-charts
  - name: ingress-nginx
    url: https://kubernetes.github.io/ingress-nginx
  - name: cloudflare
    url: https://cloudflare.github.io/helm-charts
  - name: gitea-charts
    url: https://dl.gitea.com/charts/
  - name: harbor
    url: https://helm.goharbor.io
  - name: postgres-operator-charts
    url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator
  - name: postgres-operator-ui-charts
    url: https://opensource.zalando.com/postgres-operator/charts/postgres-operator-ui
  - name: zitadel
    url: https://charts.zitadel.com

releases:
  - name: load-balancer
    namespace: infra
    chart: bitnami/metallb
    version: ~6.3.13
    wait: true
    values:
      - nameOverride: load-balancer

  - name: load-balancer-configuration
    namespace: infra
    chart: charts/load-balancer/configuration
    values:
      - values.yaml.gotmpl
      - {{ .Values | toYaml | nindent 8 }}
    needs:
      - load-balancer

  - name: cert-manager
    namespace: infra
    chart: jetstack/cert-manager
    version: v1.16.0
    wait: true
    values:
      - installCRDs: true

  - name: trust-manager
    namespace: infra
    chart: jetstack/trust-manager
    version: v0.12.0
    wait: true
    values:
      - app:
          trust:
            namespace: infra
        secretTargets:
          enabled: true
          authorizedSecrets: ["internal-ca-bundle"]
    needs:
      - cert-manager

  - name: cert-manager-configuration
    namespace: infra
    chart: charts/cert-manager/configuration
    values:
      - values.yaml.gotmpl
      - {{ .Values | toYaml | nindent 8 }}
    needs:
      - trust-manager

  - name: git-platform
    namespace: infra
    chart: gitea-charts/gitea
    version: 10.4.1
    values:
      - gitea:
          admin:
            username: gitea_admin
            password: {{ .Values.gitea.adminPassword | quote }}
          config:
            database:
              DB_TYPE: postgres
            indexer:
              ISSUE_INDEXER_TYPE: bleve
              REPO_INDEXER_ENABLED: true
        ingress:
          enabled: true
          className: internal
          annotations:
            cert-manager.io/cluster-issuer: letsencrypt
          hosts:
            - host: {{ .Values.gitea.host | quote }}
              paths:
                - path: {{ .Values.gitea.path | quote }}
                  pathType: Prefix
        redis-cluster:
          enabled: false
        redis:
          enabled: true
        postgresql:
          enabled: true
        postgresql-ha:
          enabled: false

        persistence:
          enabled: true

  - name: external-dns
    namespace: external-infra
    chart: bitnami/external-dns
    version: 8.3.7
    values:
      - provider: cloudflare
        cloudflare:
          email: {{ .Values.cloudflare.dns.email | quote }}
          apiToken: {{ .Values.cloudflare.dns.apiToken | quote }}
          proxied: false

        logLevel: debug
        domainFilters:
          - {{ .Values.cloudflare.dns.host | quote }}

        sources:
          - ingress
          - service

  - name: external-gateway-configuration
    namespace: external-infra
    chart: charts/external-gateway/configuration
    values:
      - values.yaml.gotmpl
      - {{ .Values | toYaml | nindent 8 }}
    needs:
      - infra/cert-manager

  - name: external-gateway
    namespace: external-infra
    chart: ingress-nginx/ingress-nginx
    version: 4.11.2
    values:
      - nameOverride: external-gateway
        controller:
          ingressClassResource:
            name: "external"
            controllerValue: "k8s.io/ingress-nginx"

          ingressClassByName: true
          watchIngressWithoutClass: false
          extraArgs:
            default-ssl-certificate: external-infra/external-gateway-tls

          extraVolumeMounts:
            - name: ca-certificates
              mountPath: /etc/ssl/certs/ca-certificates.crt
              subPath: ca.crt
          extraVolumes:
            - name: ca-certificates
              configMap:
                name: internal-ca-bundle
    needs:
      - external-gateway-configuration

  - name: internal-gateway-configuration
    namespace: infra
    chart: charts/internal-gateway/configuration
    values:
      - values.yaml.gotmpl
      - {{ .Values | toYaml | nindent 8 }}
    needs:
      - cert-manager

  - name: internal-gateway
    namespace: infra
    chart: ingress-nginx/ingress-nginx
    version: 4.11.2
    values:
      - nameOverride: internal-gateway
        controller:
          ingressClassResource:
            name: "internal"
            controllerValue: "k8s.io/ingress-nginx"

          ingressClassByName: true
          watchIngressWithoutClass: true
          extraArgs:
            default-ssl-certificate: infra/internal-gateway-tls

          extraVolumeMounts:
            - name: ca-certificates
              mountPath: /etc/ssl/certs/ca-certificates.crt
              subPath: ca.crt
          extraVolumes:
            - name: ca-certificates
              configMap:
                name: internal-ca-bundle
    needs:
      - internal-gateway-configuration

  - name: cloudflare-tunnel
    namespace: external-infra
    chart: cloudflare/cloudflare-tunnel
    version: 0.3.0
    values:
      - replicaCount: 1
        cloudflare:
          account: {{ .Values.cloudflare.tunnel.account | quote }}
          tunnelName: {{ .Values.cloudflare.tunnel.tunnelName | quote }}
          tunnelId: {{ .Values.cloudflare.tunnel.tunnelId | quote }}
          email: {{ .Values.cloudflare.tunnel.email | quote }}
          secret: {{ .Values.cloudflare.tunnel.secret | quote }}
          ingress:
            - hostname: {{ .Values.cloudflare.tunnel.host | quote }}
              service: https://external-gateway-controller.external-infra.svc.cluster.local
              originRequest:
                noTLSVerify: true
            - hostname: {{ printf "*.%s" .Values.cloudflare.tunnel.host | quote }}
              service: https://external-gateway-controller.external-infra.svc.cluster.local
              originRequest:
                noTLSVerify: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m"
          limits:
            memory: "128Mi"
            cpu: "200m"

  - name: image-registry
    namespace: dev-infra
    chart: harbor/harbor
    version: 1.15.1
    values:
      - expose:
          type: ingress
          tls:
            certSource: none
          ingress:
            hosts:
              core: {{ .Values.harbor.host | quote }}
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt

        externalURL: {{ printf "https://%s" .Values.harbor.host | quote }}
        harborAdminPassword: {{ .Values.harbor.adminPassword | quote }}

  - name: database-operator
    chart: postgres-operator-charts/postgres-operator
    namespace: platform
    version: 1.13.0

  - name: database-operator-ui
    chart: postgres-operator-ui-charts/postgres-operator-ui
    namespace: platform
    version: 1.13.0
    values:
      - ingress:
          enabled: true
          ingressClassName: internal
          hosts:
            - host: {{ .Values.dbOperator.host | quote }}
              paths: [ {{ .Values.dbOperator.path | quote }} ]

  - name: identity-server-configuration
    chart: charts/identity-server/configuration
    namespace: identity-infra
    values:
      - values.yaml.gotmpl
      - {{ .Values | toYaml | nindent 8 }}

  - name: identity-database
    chart: bitnami/postgresql
    namespace: identity-infra
    version: 12.10.0
    values:
      - nameOverride: identity-database
        volumePermissions:
          enabled: true
        tls:
          enabled: true
          certificatesSecret: identity-database-tls
          certFilename: "tls.crt"
          certKeyFilename: "tls.key"
        auth:
          postgresPassword: {{ .Values.identityDatabase.adminPassword }}
    needs:
      - identity-server-configuration

  - name: identity-server
    chart: zitadel/zitadel
    namespace: identity-infra
    version: 8.5.0
    values:
      - nameOverride: identity-server
        replicaCount: 1
        ingress:
          enabled: true
          className: external
          annotations:
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "true"
            external-dns.alpha.kubernetes.io/target: "53baf124-f3f5-493e-b20c-318c00aafb01.cfargotunnel.com"
            nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
          hosts:
            - host: auth.zengarden.space
              paths:
               - path: /
                 pathType: Prefix
        zitadel:
          masterkey: {{ .Values.identityServer.masterKey | quote }}
          configmapConfig:
            ExternalDomain: 'auth.zengarden.space'
            ExternalSecure: true
            TLS:
              Enabled: true
            Database:
              Postgres:
                Host: identity-database
                Port: 5432
                Database: identity-database
                MaxOpenConns: 20
                MaxIdleConns: 10
                MaxConnLifetime: 30m
                MaxConnIdleTime: 5m
                User:
                  Username: zitadel
                  SSL:
                    Mode: verify-full
                Admin:
                  Username: postgres
                  SSL:
                    Mode: verify-full
          secretConfig:
            Database:
              Postgres:
                User:
                  Password: {{ .Values.identityDatabase.userPassword }}
                Admin:
                  Password: {{ .Values.identityDatabase.adminPassword }}

          serverSslCrtSecret: identity-server-tls
          dbSslCaCrtSecret: internal-ca-bundle
    needs:
      - identity-database
      - identity-server-configuration
