apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: external-gateway
spec:
  secretName: external-gateway-tls
  issuerRef:
    name: internal-ca
    kind: ClusterIssuer
  commonName: "ext.zengarden.space"
  dnsNames:
    - "ext.zengarden.space"
    - "*.ext.zengarden.space"
