tls:
  enabled: true
  keystore:
    issuerRef:
      name: internal-ca
  truststore:
    ref:
      name: internal-ca-bundle

ingress:
  enabled: true
  className: internal
  host: earth-meter.int.zengarden.space
  path: /frontend
#  hosts:
#    - host: earth-meter.int.zengarden.space
#      paths:
#        - path: /frontend
#          pathType: ImplementationSpecific
