replicaCount: 1

port: 3000

image:
  repository: "@IMAGE_REPOSITORY@"
  pullPolicy: IfNotPresent
  tag: ""

debug:
  enabled: false
  port: 12345

tls:
  enabled: false
  keystore:
    keyPassword: changeit
    password: changeit
    certificateKey: tls.crt
    privateKeyKey: tls.key
    secretRef:
      name:
    issuerRef:
      kind: ClusterIssuer
      name:
  truststore:
    password: changeit
    ref:
      kind: ConfigMap
      name:
      key: ca-certificates.crt

env: {}

secretEnv: {}

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext:
  fsGroup: 2000

securityContext:
  capabilities:
    drop:
    - ALL
  readOnlyRootFilesystem: true
  runAsNonRoot: true
  runAsUser: 1000

service:
  type: ClusterIP
  port:

ingress:
  enabled: false
  className: ""
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 0
  periodSeconds: 30

readinessProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 0
  periodSeconds: 30

startupProbe:
  httpGet:
    path: /health
    port: http
  initialDelaySeconds: 0
  periodSeconds: 1

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

rbac:
  roles: {}
