{{- if and .Values.tls.enabled .Values.tls.keystore.issuerRef.name }}
kind: Certificate
apiVersion: cert-manager.io/v1
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  commonName: {{ include "backend.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  usages:
    - server auth
  dnsNames:
    - {{ include "backend.fullname" . }}.{{ .Release.Namespace }}.svc.cluster.local
  secretName: {{ include "backend.fullname" . }}-tls
  issuerRef:
    {{- toYaml .Values.tls.keystore.issuerRef | nindent 4 }}
{{- end }}
