apiVersion: v1
kind: Secret
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
stringData:
{{- range $key, $value :=  .Values.secretEnv }}
  {{ $key | quote }}: {{ $value | quote }}
{{- end }}
