dev: true
spring:
  datasource:
    url: jdbc:postgresql:postgres
    username: postgres
    password: password
    # docker run -p 5432:5432 --name postgres -e POSTGRES_PASSWORD=password -d postgres

  security:
    oauth2:
      resourceserver:
        opaque-token:
          introspection-uri: https://auth.zengarden.space/oauth/v2/introspect
          client-id: 291183786706665551
          client-secret: CwRseTRlHfJB06F3gsSu0F51FCkuEOdbPXkBevWe4PHPPxutYaF1i4CgnWEa7yAK
